### PR TITLE
Error handling and maintenance mode fixes

### PR DESCRIPTION
**Pull request by danmactough**
- changes the maintenance mode page's status code to 503
- makes cluster workers get the current maintenance mode from the cluster master before stating the gateway (we were having workers error out and die going into maintenance mode, then coming back up in non-maintenance mode)
- fixes all the error handling

### CODE REVIEW

**Comment by carlos8f** [comment]
Looks reasonable, I'll merge then fix the style things.

Thanks!

**Comment by danmactough** [comment]
Oh, okay. Cool. I was just about to clean those up now that github has returned for us here.

**Comment by carlos8f** [comment]
Also, would be nice to have maintenance mode tests to ensure the messaging mechanism continues to work.

**Comment by carlos8f** [comment]
published v1.4.2

**Comment by carlos8f** [comment]
whoops, don't use v1.4.2 yet, lol

**Comment by carlos8f** [comment]
ok, published v1.4.3 now

**Pull request merged**
