### PR TITLE
Upgrade http-proxy and fix engine.io upgrades.

### PR DESCRIPTION
**Pull request by danmactough**
Pretty straightforward update to http-proxy v1.0.2 from v0.8.x notwithstanding the total overhaul:
https://github.com/nodejitsu/node-http-proxy/blob/master/UPGRADING.md

I was not able to track down what exactly was broken. In any event, this fixes it.

Tests pass (notwithstanding Travis). I'll add another test for the websockets, but I wanted to get this in front of you asap.

### CODE REVIEW

**Comment by danmactough** [comment]
FYI @cpsubrian (since @carlos8f and I discussed over IM) -- amino-gateway currently does not handle websocket upgrades due to http-proxy v0.8 failing for some reason. There was actually an open issue: https://github.com/nodejitsu/node-http-proxy/issues/447 Not much info. for them to go on, obviously.

**Comment by carlos8f** [comment]
good catch, i knew it was some stupid regression like this...

**Comment by carlos8f** [comment]
published in v1.4.1, thanks @danmactough !

**Comment by carlos8f** [comment]
unfortunately this broke node 0.8 support. At this point I am going to drop the support rather than dual support http-proxy versions.

**Comment by danmactough** [comment]
Seems reasonable.

**Comment by cpsubrian** [comment]
Mental note to be careful about upgrading any live 0.8 sites (live events?, intl?)

**Comment by danmactough** [comment]
Maybe we should revert to a known working state on v0.8 and make it EOL of the v1.4.x amino-gateway branch. Then make this (breaking change -- node v0.10 only) v1.5.

**Pull request merged**
